# -*- coding: utf-8 -*-
"""VPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvotwUKCNHrFYaeMhanwZXJYnjKdJY3Z
"""

from __future__ import annotations

import base64
import json
import os
import time
import uuid
from dataclasses import dataclass
from typing import Any, Dict, Tuple

import requests

JsonDict = Dict[str, Any]


@dataclass(frozen=True)
class Endpoints:
    access_control_url: str
    avs_query_url: str
    pacc_anonymize_url: str


def now_utc() -> str:
    return time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())


def new_request_id() -> str:
    return uuid.uuid4().hex


def post_json(url: str, payload: JsonDict, timeout_seconds: float) -> JsonDict:
    r = requests.post(url, json=payload, timeout=timeout_seconds)
    r.raise_for_status()
    return r.json()


def split_request(vpi_request: JsonDict) -> Tuple[JsonDict, JsonDict]:
    query = vpi_request.get("query") or {}

    avs_request: JsonDict = {
        "request_id": vpi_request["request_id"],
        "app_id": vpi_request["app_id"],
        "timestamp": vpi_request["timestamp"],
        "query": {
            "time_range": query.get("time_range"),
            "regions_of_interest": query.get("regions_of_interest", []),
        },
    }

    pacc_instruction: JsonDict = {
        "request_id": vpi_request["request_id"],
        "app_id": vpi_request["app_id"],
        "timestamp": vpi_request["timestamp"],
        "object_queries": query.get("object_queries", []),
        "output_format": vpi_request.get("output_format", {}),
    }

    return avs_request, pacc_instruction


def handle_vpi_request(vpi_request: JsonDict, endpoints: Endpoints, timeout_seconds: float = 12.0) -> JsonDict:
    vpi_request = dict(vpi_request)
    vpi_request["request_id"] = vpi_request.get("request_id") or new_request_id()
    vpi_request["timestamp"] = vpi_request.get("timestamp") or now_utc()

    if not vpi_request.get("app_id"):
        return {"decision": "deny", "reason": "missing_app_id", "request_id": vpi_request["request_id"]}

    access_payload: JsonDict = {
        "request_id": vpi_request["request_id"],
        "app_id": vpi_request["app_id"],
        "timestamp": vpi_request["timestamp"],
        "signature": vpi_request.get("signature", ""),
        "query": vpi_request.get("query", {}),
        "output_format": vpi_request.get("output_format", {}),
    }
    decision = post_json(endpoints.access_control_url, access_payload, timeout_seconds)

    if decision.get("decision") != "allow":
        return {
            "request_id": vpi_request["request_id"],
            "app_id": vpi_request["app_id"],
            "timestamp": vpi_request["timestamp"],
            "decision": "deny",
            "reason": decision.get("reason", "denied"),
        }

    avs_request, pacc_instruction = split_request(vpi_request)

    avs_result = post_json(endpoints.avs_query_url, avs_request, timeout_seconds)

    pacc_payload: JsonDict = {
        "instruction": pacc_instruction,
        "avs_result": avs_result,
        "access_context": decision.get("access_context", {}),
    }
    pacc_result = post_json(endpoints.pacc_anonymize_url, pacc_payload, timeout_seconds)

    return {
        "request_id": vpi_request["request_id"],
        "app_id": vpi_request["app_id"],
        "timestamp": vpi_request["timestamp"],
        "decision": "allow",
        "result": pacc_result,
    }


def lambda_handler(event: JsonDict, context: Any) -> JsonDict:
    endpoints = Endpoints(
        access_control_url=os.environ["ACCESS_CONTROL_URL"],
        avs_query_url=os.environ["AVS_QUERY_URL"],
        pacc_anonymize_url=os.environ["PACC_ANONYMIZE_URL"],
    )
    timeout_seconds = float(os.getenv("REQUEST_TIMEOUT_SECONDS", "12"))

    body = event.get("body") or "{}"
    if event.get("isBase64Encoded"):
        body = base64.b64decode(body).decode("utf8")

    try:
        vpi_request = json.loads(body)
        result = handle_vpi_request(vpi_request, endpoints, timeout_seconds)
        return {"statusCode": 200, "headers": {"Content-Type": "application/json"}, "body": json.dumps(result)}
    except requests.HTTPError as e:
        return {
            "statusCode": 502,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"error": "upstream_http_error", "detail": str(e)}),
        }
    except Exception as e:
        return {
            "statusCode": 500,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"error": "internal_error", "detail": str(e)}),
        }

def main() -> None:
    """
    Google Colab runnable demo.
    No environment variables.
    No external services.
    Fully self-contained PaCC + VPI flow.
    """

    # -----------------------------
    # Mock cloud services
    # -----------------------------

    def mock_access_control(payload: JsonDict) -> JsonDict:
        # Simulate Access Control Engine decision
        return {
            "decision": "allow",
            "access_context": {
                "policy_id": "demo_policy_v1",
                "approved_objects": ["license_plate", "pedestrian"],
            },
        }

    def mock_avs_query(payload: JsonDict) -> JsonDict:
        # Simulate encrypted AVS lookup
        return {
            "records": [
                {
                    "record_id": "frame_0001",
                    "timestamp": "20251014T090010Z",
                    "ciphertext_ref": "avs://encrypted/blob/0001",
                },
                {
                    "record_id": "frame_0002",
                    "timestamp": "20251014T090020Z",
                    "ciphertext_ref": "avs://encrypted/blob/0002",
                },
            ]
        }

    def mock_pacc_anonymize(payload: JsonDict) -> JsonDict:
        # Simulate PaCC confidential execution + anonymization
        return {
            "frames": [
                {
                    "timestamp": "20251014T090010Z",
                    "objects": [
                        {
                            "query_id": "q1",
                            "type": "license_plate",
                            "bbox": [0.12, 0.30, 0.18, 0.36],
                            "confidence": 0.93,
                        }
                    ],
                },
                {
                    "timestamp": "20251014T090020Z",
                    "objects": [
                        {
                            "query_id": "q2",
                            "type": "pedestrian",
                            "bbox": [0.45, 0.20, 0.60, 0.85],
                            "confidence": 0.88,
                        }
                    ],
                },
            ]
        }

    # -----------------------------
    # Demo VPI request
    # -----------------------------

    vpi_request: JsonDict = {
        "request_id": new_request_id(),
        "app_id": "third_party_app_identifier",
        "timestamp": now_utc(),
        "signature": "DEMO_SIGNATURE",
        "query": {
            "time_range": {
                "start": "20251014T090000Z",
                "end": "20251014T100000Z",
            },
            "regions_of_interest": ["front_camera", "rear_camera"],
            "object_queries": [
                {
                    "query_id": "q1",
                    "object_type": "license_plate",
                    "attributes": {
                        "state": ["CA", "NY"],
                        "confidence_threshold": 0.85,
                    },
                },
                {
                    "query_id": "q2",
                    "object_type": "pedestrian",
                    "attributes": {
                        "age_range": ["adult"],
                    },
                },
            ],
        },
        "output_format": {
            "type": "structured_data",
            "include_confidence_scores": True,
            "coordinate_system": "normalized",
        },
    }

    # -----------------------------
    # PaCC execution flow
    # -----------------------------

    print("=== Step 1: Access Control ===")
    decision = mock_access_control(vpi_request)
    print(json.dumps(decision, indent=2))

    if decision["decision"] != "allow":
        print("Request denied")
        return

    print("\n=== Step 2: Split VPI Request ===")
    avs_request, pacc_instruction = split_request(vpi_request)
    print("AVS Request:")
    print(json.dumps(avs_request, indent=2))
    print("\nPaCC Instruction:")
    print(json.dumps(pacc_instruction, indent=2))

    print("\n=== Step 3: AVS Query ===")
    avs_result = mock_avs_query(avs_request)
    print(json.dumps(avs_result, indent=2))

    print("\n=== Step 4: PaCC Anonymization ===")
    pacc_payload = {
        "instruction": pacc_instruction,
        "avs_result": avs_result,
        "access_context": decision["access_context"],
    }
    pacc_result = mock_pacc_anonymize(pacc_payload)
    print(json.dumps(pacc_result, indent=2))

    print("\n=== Final Response to Application ===")
    final_response = {
        "request_id": vpi_request["request_id"],
        "app_id": vpi_request["app_id"],
        "decision": "allow",
        "result": pacc_result,
    }
    print(json.dumps(final_response, indent=2))

main()