const {chromium} = require('playwright');
const fs = require('fs');
const assert = require('assert');
(async()=>{
 const root=require('path').resolve(__dirname,'../host/viewer');
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1500,height:1000}});
 await page.route('**/*',route=>route.abort());
 const html=fs.readFileSync(root+'/index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
 await page.setContent(html);
 await page.evaluate(()=>document.getElementById('loginScreen')?.classList.remove('visible'));
 await page.addStyleTag({content:fs.readFileSync(root+'/styles.css','utf8')});
 let app=fs.readFileSync(root+'/app.js','utf8').replace(/^import .*;\n/gm,'').replace(/\nboot\(\);\s*$/,'');
 app+=`\nwindow.testApi={state,loadTimeline,renderBrakeEvents,drawTimeline,setupTimeline};
 scheduleSensorLoad=()=>{window.lastSelection=state.selectedNs;};
 window.mockTimeline=(value)=>{fetchJson=async()=>value;};`;
 await page.addScriptTag({content:app});
 const result=await page.evaluate(async()=>{
  const {state,setupTimeline,loadTimeline}=testApi;
  const start='1789387200000000000';const end='1789387209900000000';
  const trip={id:'2026-09-14-trip_99',label:'Brake marker test',start_ns:start,end_ns:end,duration_ns:'9900000000',candidate_bytes:1000,modalities:[]};
  state.trip=trip;state.trips=[trip];state.role='incident_investigator';state.selectedNs=start;
  const events=[{timestamp_ns:'1789387202000000000'},{timestamp_ns:'1789387207000000000'}];
  mockTimeline({tracks:{},access:{position:{authorized:true},'camera.front':{authorized:true},'lidar.top':{authorized:true}},hard_braking:{status:'ready',events}});
  setupTimeline();await loadTimeline();
  const canvas=document.getElementById('timeline');const rect=canvas.getBoundingClientRect();
  const x=112+(rect.width-24-112)*2/9.9;
  const pixel=Array.from(canvas.getContext('2d').getImageData(Math.round(x),60,1,1).data);
  return {x:rect.left+x,y:rect.top+60,pixel,optionCount:document.getElementById('brakeEventSelect').options.length};
 });
 assert.equal(result.optionCount,3);
 assert(result.pixel[0]>240 && result.pixel[1]<100 && result.pixel[2]<100,JSON.stringify(result));
 await page.mouse.click(result.x+3,result.y);
 assert.equal(await page.evaluate(()=>window.lastSelection),'1789387202000000000');
 await page.selectOption('#brakeEventSelect','1789387207000000000');
 assert.equal(await page.evaluate(()=>window.lastSelection),'1789387207000000000');
 await page.locator('.timeline-panel').screenshot({path:require('path').join(require('os').tmpdir(),'pdal-hard-brake-timeline.png')});
 await page.evaluate(async()=>{mockTimeline({tracks:{},access:{},hard_braking:{status:'denied',events:[]}});await testApi.loadTimeline();});
 assert(await page.locator('#brakeEventSelect').isHidden());
 assert((await page.locator('#timelineHint').innerText()).includes('restricted'));
 const stale=await page.evaluate(async()=>{
  let complete;fetchJson=()=>new Promise(resolve=>complete=resolve);
  const pending=testApi.loadTimeline();testApi.state.trip={...testApi.state.trip,id:'other'};
  complete({tracks:{},access:{},hard_braking:{status:'ready',events:[{timestamp_ns:'1'}]}});
  await pending;return testApi.state.brakeEvents.length;
 });
 assert.equal(stale,0);
 fs.writeFileSync(require('path').join(require('os').tmpdir(),'pdal-browser-result.json'),JSON.stringify({red_lines_verified:true,click_exact_timestamp:true,dropdown_exact_timestamp:true,denied_markers_hidden:true,stale_trip_response_ignored:true},null,2)+'\n');
 console.log('Browser timeline tests passed');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
