<?xml version="1.0"?>
<package format="3">
  <name>bring_up</name>
  <version>0.1.0</version>
  <description>
    Brings up ingest and retrieve executables that link against avs and pacc.
  </description>

  <maintainer email="yuxw@udel.edu">Yuxin Wang</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>

  <depend>avs</depend>
  <depend>pacc</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
