common:
  img_ssd_dir: /home/avs/DATA/SSD/images
  lidar_ssd_dir: /home/avs/DATA/SSD/lidar
  gps_ssd_dir: /home/avs/DATA/SSD/gps
  img_hdd_dir: /home/avs/DATA/HDD/images
  lidar_hdd_dir: /home/avs/DATA/HDD/lidar
  gps_hdd_dir: /home/avs/DATA/HDD/gps
  
  hot_db_dir:  /home/avs/DATA/SSD/db
  cold_db_dir: /home/avs/DATA/HDD/db

  img_topic: /my_camera/pylon_ros2_camera_node/image_raw  #/camera/image for KITTI
  lidar_topic:  /sensing/lidar/top/pointcloud      #/lidar/pointcloud for KITTI
  gps_topic: /novatel/oem7/gps

image_dedup:    # Deduplicate image and save each image to ssd
  hamming_threshold: 2
  img_format: jpg     # "jpg" or "png"
  img_quality: 95       # 0–100 for jpg, 0–9 for png

# image_compress:  # Compress image sequence and save to hdd
#   fps: 10               # KITTI image publish rate is 10Hz, adjust it according to your camera frequency
#   segment_duration_sec: 1   # Suggest segement length

# lidar_downsample:  # Downsample raw lidar point cloud with voxel grid filter
#   leaf_size: 0.2        # 0 to 0.3 recommand

# lidar_compress:
#   lidar_format: laz
