common:
  img_topic: /camera/image_raw  # KITTI tracking 0000

  ssd_root: /home/avs/DATA/SSD/PaCC

image_dedup:    # Deduplicate image and save each image to ssd
  hamming_threshold: 2
  img_format: jpg     # "jpg" or "png"
  img_quality: 95       # 0–100 for jpg, 0–9 for png

image_compress:  # Compress image sequence and save to hdd
  fps: 10               # KITTI image publish rate is 10Hz, adjust it according to your camera frequency
  segment_duration_sec: 1   # Suggest segement length

crypto:
  enabled: true

  # If the file exists, load it. If it does not exist and generate_if_missing is true,
  # a new key will be generated and saved here.
  key_path: /home/avs/PaCC/keys/aes_gcm.key
  generate_if_missing: true
